version: "3.4"
services:
  swim-team-manager-database:
    # build: ./database
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: cpierswim/swim-team-manager-database:1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  swim-team-manager-backend:
    # build: ./backend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: cpierswim/swim-team-manager-backend:1.0
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - "swim-team-manager-database"
    command: >
      sh -c "flask db upgrade && gunicorn -w 4 -b 0.0.0.0 app:app"
  swim-team-manager-frontend:
    # build: ./frontend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: cpierswim/swim-team-manager-frontend:1.0
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    depends_on:
      - "swim-team-manager-backend"
volumes:
  db-data:
