"""empty message

Revision ID: 5bdc2ef04060
Revises: 50ffea01b254
Create Date: 2023-04-26 21:09:52.095250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdc2ef04060'
down_revision = '50ffea01b254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meet', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
