"""empty message

Revision ID: 7b6ade3a0ce9
Revises: a79854193dc5
Create Date: 2023-05-07 15:42:29.164740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6ade3a0ce9'
down_revision = 'a79854193dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relay', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
