"""empty message

Revision ID: 938e3ead801e
Revises: 0ebda8957ad3
Create Date: 2023-05-05 18:11:47.965865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e3ead801e'
down_revision = '0ebda8957ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('meet_id')

    op.drop_table('environment')
    # ### end Alembic commands ###
