"""Init

Revision ID: a8c574b55039
Revises: 
Create Date: 2023-04-25 16:21:58.424503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c574b55039'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line_one', sa.String(length=255), nullable=False),
    sa.Column('address_line_two', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_coach',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'coach_id')
    )
    op.create_table('meet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('age_up_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relay_identifier', sa.String(length=2), nullable=False),
    sa.Column('swimmer1', sa.Integer(), nullable=True),
    sa.Column('swimmer2', sa.Integer(), nullable=True),
    sa.Column('swimmer3', sa.Integer(), nullable=True),
    sa.Column('swimmer4', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('coach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isHeadCoach', sa.Boolean(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('stroke', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=1), nullable=False),
    sa.Column('event_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('DQCode', sa.String(length=3), nullable=True),
    sa.Column('swimmer1', sa.Integer(), nullable=True),
    sa.Column('swimmer2', sa.Integer(), nullable=True),
    sa.Column('swimmer3', sa.Integer(), nullable=True),
    sa.Column('swimmer4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['meet_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swimmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('preferred_first_name', sa.String(length=25), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('swimmer_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('exhibition', sa.Boolean(), nullable=False),
    sa.Column('bonus', sa.Boolean(), nullable=False),
    sa.Column('entry_type', sa.String(length=1), nullable=True),
    sa.Column('relay_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['meet_event.id'], ),
    sa.ForeignKeyConstraint(['relay_id'], ['relay.id'], ),
    sa.ForeignKeyConstraint(['swimmer_id'], ['swimmer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('swimmer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['swimmer_id'], ['swimmer.id'], ),
    sa.PrimaryKeyConstraint('family_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family')
    op.drop_table('entry')
    op.drop_table('swimmer')
    op.drop_table('result')
    op.drop_table('parent')
    op.drop_table('meet_event')
    op.drop_table('group')
    op.drop_table('coach')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('relay')
    op.drop_table('meet')
    op.drop_table('group_coach')
    op.drop_table('address')
    # ### end Alembic commands ###
