"""empty message

Revision ID: ad62d8748883
Revises: b45c76cc991e
Create Date: 2023-04-28 00:37:07.226160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad62d8748883'
down_revision = 'b45c76cc991e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('swimmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer', schema=None) as batch_op:
        batch_op.drop_column('family_id')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
