"""empty message

Revision ID: b45c76cc991e
Revises: ae1da9897c46
Create Date: 2023-04-27 23:54:51.580856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45c76cc991e'
down_revision = 'ae1da9897c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_family_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_family_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_family_id')
    # ### end Alembic commands ###
