"""empty message

Revision ID: bdf5c386a32d
Revises: 1d4c414537c9
Create Date: 2023-04-27 11:16:19.176915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf5c386a32d'
down_revision = '1d4c414537c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('result_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'entry', ['entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('result_ibfk_1', 'meet_event', ['entry_id'], ['id'])

    # ### end Alembic commands ###
