"""empty message

Revision ID: d619d40a0d6d
Revises: d3c5a0fd7510
Create Date: 2023-05-03 17:07:44.831229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd619d40a0d6d'
down_revision = 'd3c5a0fd7510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('entry_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('result_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_foreign_key('result_ibfk_1', 'entry', ['entry_id'], ['id'])
        batch_op.alter_column('entry_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
