"""Update 1

Revision ID: d9164b4b500b
Revises: a8c574b55039
Create Date: 2023-04-26 13:49:13.278009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9164b4b500b'
down_revision = 'a8c574b55039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('entry_type',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('relay_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('meet', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])

    with op.batch_alter_table('relay', schema=None) as batch_op:
        batch_op.drop_column('time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('relay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('meet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('relationship_id')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('relay_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('entry_type',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###
